import requests
import time
import json
import re
import os
from dotenv import load_dotenv

# Load environment variables (support local run and start.sh synced runs)
load_dotenv(os.path.join(os.path.dirname(__file__), ".env"))
load_dotenv(os.path.join(os.path.dirname(os.path.dirname(__file__)), ".env"))

CACHE_FILE = os.path.join(os.path.dirname(__file__), "synonym_cache.json")

def load_synonym_cache():
    if os.path.exists(CACHE_FILE):
        try:
            with open(CACHE_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            print(f"Error loading cache: {e}")
    return {}

def save_synonym_cache(cache):
    try:
        with open(CACHE_FILE, "w", encoding="utf-8") as f:
            json.dump(cache, f, indent=2, ensure_ascii=False)
    except Exception as e:
        print(f"Error saving cache: {e}")

_synonym_cache = load_synonym_cache()

# --- Provider configuration from .env ---
LLM_PROVIDER = os.getenv("LLM_PROVIDER", "local").lower().strip()
if LLM_PROVIDER == "lmstudio":
    LLM_PROVIDER = "local"

PROVIDER_CONFIG = {
    "local": {
        "url": os.getenv("LM_STUDIO_URL", "http://127.0.0.1:1234/v1/chat/completions"),
        "model": os.getenv("LM_STUDIO_MODEL_FAST", os.getenv("LM_STUDIO_MODEL", "qwen/qwen3-1.7b")),
        "api_key": None,
    },
    "mistral": {
        "url": "https://api.mistral.ai/v1/chat/completions",
        "model": os.getenv("MISTRAL_MODEL", "mistral-large-2411"),
        "api_key": os.getenv("MISTRAL_API_KEY", ""),
    },
    "openai": {
        "url": "https://api.openai.com/v1/chat/completions",
        "model": os.getenv("OPENAI_MODEL", "gpt-4o-mini"),
        "api_key": os.getenv("OPENAI_API_KEY", ""),
    },
}

def _get_provider():
    """Return the active provider config, falling back to local if unknown."""
    cfg = PROVIDER_CONFIG.get(LLM_PROVIDER)
    if cfg is None:
        print(f"Warning: unknown LLM_PROVIDER '{LLM_PROVIDER}', falling back to local")
        return PROVIDER_CONFIG["local"]
    return cfg

print(f"--- LLM Provider: {LLM_PROVIDER} ---")


def call_fast_llm(prompt: str, temp: float = 0.3) -> str:
    """Send a prompt to the configured LLM provider and return the response text."""
    cfg = _get_provider()

    headers = {"Content-Type": "application/json"}
    if cfg["api_key"]:
        headers["Authorization"] = f"Bearer {cfg['api_key']}"

    payload = {
        "model": cfg["model"],
        "messages": [
            {"role": "user", "content": prompt}
        ],
        "temperature": temp,
        "max_tokens": 200,
    }

    res = requests.post(cfg["url"], json=payload, headers=headers, timeout=30)
    res.raise_for_status()
    text = res.json()['choices'][0]['message']['content']
    return re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL).strip()

def get_contextual_synonyms(sentence: str, word: str, language: str = 'en'):
    """
    Asks the configured LLM for contextual synonyms for a word in a sentence.
    Checks the cache first to avoid redundant calls.
    """
    word_key = word.lower().strip()
    
    # 1. Check Cache
    if language in _synonym_cache and word_key in _synonym_cache[language]:
        print(f"--- CACHE HIT: '{word}' ({language}) ---")
        return _synonym_cache[language][word_key]

    prompt = f"""In {language}, list up to 30 single-word that could replace "{word}" in: "{sentence}". 
Each replacement must be exactly ONE word. Return ONLY a comma-separated list. No preamble. /no_think"""

    print(f"\n--- CONTEXTUAL SYNONYMS ({LLM_PROVIDER}) ---\n{prompt}\n----------------------------------")

    try:
        result = call_fast_llm(prompt, temp=0.5)
        # Remove <think>...</think> tags which are occasionally generated by reasoning models
        result = re.sub(r'<think>.*?</think>', '', result, flags=re.DOTALL).strip()
        
        synonyms = [s.strip().replace('"', '') for s in result.split(',') if s.strip()]
        # Filter out multi-word entries, deduplicate (preserving order), and limit to 30
        seen = set()
        deduped_syns = []
        for s in synonyms:
            s_clean = s.strip()
            if ' ' not in s_clean and s_clean.lower() not in seen:
                deduped_syns.append(s_clean)
                seen.add(s_clean.lower())
        synonyms = deduped_syns[:30]
        
        # 2. Update Cache
        if language not in _synonym_cache:
            _synonym_cache[language] = {}
        _synonym_cache[language][word_key] = synonyms
        save_synonym_cache(_synonym_cache)
        
        return synonyms
    except Exception as e:
        print(f"Error in contextual synonyms: {e}")
        return []
