// ============================================================
// TextBand V2 — Core Types
// ============================================================

export interface SynonymSegment {
  begin: string[];
  mid: string[];
  end: string[];
}

export interface WordSynonyms {
  original: string;
  currentText?: string;
  originalPhonemes?: string[];
  synonyms: {
    text: string;
    segments: SynonymSegment;
  }[];
}

/** A single text block in the text track */
export interface TextBlock {
  id: string;
  text: string;
  /** Width in timeline units (proportional to char count) */
  width: number;
  /** Phonemes for this block, fetched from backend */
  phonemes?: { text: string; phonemes: string[] }[];
  /** Synonym bank for each word in this block */
  synonymBank?: WordSynonyms[];
  /** True if this block is currently being phonemized */
  isPhonemizing?: boolean;
  /** True if this block is currently being regenerated by AI */
  isRegenerating?: boolean;
}

/** Supported languages */
export type Language = 'en' | 'fr';

/** Brush types for MIDI grid interaction */
export type BrushType = 'positive' | 'negative';

/** Phonetic sections for word-based MIDI */
export type PhoneticSection = 'begin' | 'mid' | 'end';

/** Sort modes for MIDI tracks */
export type PhonemeSortMode = 'default' | 'popularity-lang' | 'popularity-text' | 'selected';

/** A single phoneme occurrence in the MIDI representation */
export interface PhonemeEvent {
  /** The IPA symbol */
  phoneme: string;
  /** Start position in the text (character index) */
  startChar: number;
  /** End position in the text (character index) */
  endChar: number;
  /** Exact pixel start position for rendering */
  startPx?: number;
  /** Exact pixel end position for rendering */
  endPx?: number;
  /** Original text characters associated with this phoneme */
  textStr?: string;
  /** Row index in the MIDI grid (based on phonetics.json order) */
  row: number;
  /** Block ID this phoneme belongs to */
  blockId?: string;
  /** Whether this is a user-imposed constraint */
  constraintType?: BrushType;
}

/** MIDI track data for a single phoneme lane */
export interface MidiLane {
  phoneme: string;
  row: number;
  events: PhonemeEvent[];
}

export interface DAWState {
  blocks: TextBlock[];
  language: Language;
  tempo: number; // words per minute for TTS
  isPlaying: boolean;
  playingPhoneme?: string | null;
  selectedBlockId: string | null;

  /** 
   * MIDI Constraints per phoneme, word and section.
   * Maps phoneme -> "blockId:wordIdx" -> section -> brushType
   */
  midiOverrides?: Record<string, Record<string, Record<string, BrushType>>>;
  /** Loop start/end in pixels */
  loopRegion: [number, number] | null;
  /** Currently copied block for paste operations */
  copiedBlock: TextBlock | null;
  /** Width in pixels for the whole timeline track (usually recalculated) */
  totalWidth?: number;
  /** Current phoneme sorting mode */
  phonemeSortMode: PhonemeSortMode;
}

/** Action types for the DAW reducer */
export type DAWAction =
  | { type: 'SET_BLOCKS'; blocks: TextBlock[] }
  | { type: 'UPDATE_BLOCK'; id: string; text: string; width?: number }
  | { type: 'UPDATE_BLOCK_PHONEMES'; id: string; phonemes: { text: string; phonemes: string[] }[] }
  | { type: 'SET_BLOCK_PHONEMIZING'; id: string; isPhonemizing: boolean }
  | { type: 'ADD_BLOCK'; block: TextBlock }
  | { type: 'REMOVE_BLOCK'; id: string }
  | { type: 'REORDER_BLOCKS'; activeId: string; overId: string }
  | { type: 'SPLIT_BLOCK'; id: string; leftText: string; rightText: string }
  | { type: 'SET_LANGUAGE'; language: Language }
  | { type: 'SET_TEMPO'; tempo: number }
  | { type: 'SET_PLAYING'; isPlaying: boolean }
  | { type: 'SET_PLAYING_PHONEME'; phoneme: string | null }
  | { type: 'SELECT_BLOCK'; id: string | null }
  | { type: 'TOGGLE_MIDI_NOTE'; phoneme: string; wordKey: string; section: string; brush: BrushType }
  | { type: 'UPDATE_BLOCK_SYNONYMS'; id: string; synonymBank: WordSynonyms[] }
  | { type: 'RESET_MIDI' }
  | { type: 'SET_BLOCK_LOADING'; id: string; isLoading: boolean }
  | { type: 'REPLACE_BLOCK_WITH_SEGMENTS'; id: string; segments: TextBlock[] }
  | { type: 'MERGE_BLOCKS'; id1: string; id2: string; mergedBlock: TextBlock }
  | { type: 'SET_LOOP_REGION'; region: [number, number] | null }
  | { type: 'COPY_SELECTED_BLOCK' }
  | { type: 'PASTE_COPIED_BLOCK' }
  | { type: 'UPDATE_BLOCK_WIDTH'; id: string; width: number }
  | { type: 'SELECT_SYNONYM'; id: string; wIdx: number; newWord: string }
  | { type: 'SET_PHONEME_SORT_MODE'; mode: PhonemeSortMode };
